name: Recent Activity

on:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JasonEtco/activity-box@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
